spring:
  application:
    name: user
  datasource:
    url: jdbc:postgresql://localhost:5435/ms-user-ms
    username: postgres-user
    password: postgres-password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    addresses: amqps://jaragua.lmq.cloudamqp.com
    username: lvngqwje
    password: SvWvCzvjOV5PcVYu7uqRUi2wVeN3NtrS
    virtual-host: lvngqwje

server:
  port: 8081