spring:
  application:
    name: email
  datasource:
    url: jdbc:postgresql://localhost:5433/ms_email_ms
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
    ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    addresses: amqps://jaragua.lmq.cloudamqp.com
    username: lvngqwje
    password: SvWvCzvjOV5PcVYu7uqRUi2wVeN3NtrS
    virtual-host: lvngqwje

server:
  port: 8080
